backend:
  name: github
  repo: Crativo/before-landing
  branch: "master"
collections:
  - label: "People"
    name: "people"
    folder: "src/people"
    create: true
    slug: "{{field.fname}}-{{field.lname}}"
    fields:
      - { label: "Title", name: "title", widget: "hidden" }
      - { label: "First Name", name: "fname", widget: string }
      - { label: "Last Name", name: "lname", widget: string }
      - { label: "Position", name: "position", widget: string }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Landing Page"
        name: "landing"
        file: "src/pages/landing.json"
        fields:
          - {label: PageHeadline, name: pageHeadline, widget: string}
          - label: "Social Links"
            name: "social"
            widget: "list"
            fields:
              - label: Network
                name: network
                widget: select
                options:
                - { label: "Facebook", value: "facebook" }
                - { label: "Instagram", value: "instagram" }
                - { label: "LinkedIn", value: "linkedin" }
              - {label: Link, name: link, widget: string}
      - label: "Work Page"
        name: "work"
        file: "src/pages/work.json"
        fields:
          - {label: PageHeadline, name: pageHeadline, widget: string}
          - label: "Case Studies"
            name: "caseStudies"
            widget: "list"
            fields:
              - label: Study
                name: study
                widget: list
                fields:
                - { label: "Brand Name", value: "brandName" }
                - { label: "Work Type", value: "workType" }
      - label: "About Page"
        name: "about"
        file: "src/pages/about.json"
        fields:
          - {label: PageHeadline, name: pageHeadline, widget: string}
media_folder: static/img
public_folder: /img