backend:
  name: github
  repo: Crativo/before-landing
  branch: 'master'
collections:
  - label: 'Case Studies'
    name: 'caseStudies'
    folder: 'src/case-studies'
    create: true
    slug: '{{slug}}'
    identifier_field: brandName
    extension: json
    fields:
      - {
          label: 'Position',
          name: 'position',
          widget: number,
          default: 0,
          valueType: 'int',
          min: 0,
          max: 200,
        }
      - { label: 'Page Headline', name: 'brandPageHeadline', widget: string }
      - { label: 'Slug', name: 'slug', widget: string }
      - { label: 'Brand Name', name: 'brandName', widget: string }
      - { label: 'Work Type', name: 'workType', widget: string }
      - { label: 'Work Details', name: 'workDetails', widget: string }
      - {
          label: 'Cover Image Horizontal',
          name: 'coverImageHorizontal',
          widget: image,
          required: false,
        }
      - {
          label: 'Cover Image Square',
          name: 'coverImageSquare',
          widget: image,
          required: false,
        }
      - {
          label: 'Row/Col Spacing (px)',
          name: 'spacing',
          widget: number,
          default: 0,
          valueType: 'int',
          min: 0,
          max: 200,
        }
      - label: 'Rows'
        name: 'rows'
        widget: list
        fields:
          - label: 'Cols'
            name: 'cols'
            widget: list
            fields:
              - { label: 'Image Item', name: 'imageSrc', widget: image }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Landing Page'
        name: 'landing'
        file: 'src/pages/landing.json'
        fields:
          - label: 'PageHeadline'
            name: 'pageHeadline'
            widget: string
          - label: 'Social Links'
            name: 'social'
            widget: 'list'
            fields:
              - label: Network
                name: network
                widget: select
                options:
                  - { label: 'Facebook', value: 'facebook' }
                  - { label: 'Instagram', value: 'instagram' }
                  - { label: 'LinkedIn', value: 'linkedin' }
              - { label: Link, name: link, widget: string }
media_folder: static/img
public_folder: /img
