backend:
  name: github
  repo: Crativo/before-landing
  branch: "master"
collections:
  - label: "People"
    name: "people"
    folder: "src/people"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: string }
      - { label: "Position", name: "position", widget: string }
  - label: "Case Studies"
    name: "caseStudies"
    folder: "src/case-studies"
    create: true
    slug: "{{slug}}"
    identifier_field: brandName
    fields:
      - { label: "Brand Name", name: "brandName", widget: string }
      - { label: "Work Type", name: "workType", widget: string }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Landing Page"
        name: "landing"
        file: "src/pages/landing.json"
        fields:
          - {label: PageHeadline, name: pageHeadline, widget: string}
          - label: "Social Links"
            name: "social"
            widget: "list"
            fields:
              - label: Network
                name: network
                widget: select
                options:
                - { label: "Facebook", value: "facebook" }
                - { label: "Instagram", value: "instagram" }
                - { label: "LinkedIn", value: "linkedin" }
              - {label: Link, name: link, widget: string}
      - label: "Work Page"
        name: "work"
        file: "src/pages/work.json"
        fields:
          - {label: PageHeadline, name: pageHeadline, widget: string}
      - label: "About Page"
        name: "about"
        file: "src/pages/about.json"
        fields:
          - {label: PageHeadline, name: pageHeadline, widget: string}
media_folder: static/img
public_folder: /img